

insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (1, 500, 100, 200, 1);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (2, 1000, 100, 200, 1);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (3, 1500, 100, 200, 1);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (4, 2000, 100, 200, 1);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (5, 2500, 100, 200, 1);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (6, 3000, 100, 200, 2);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (7, 3500, 100, 200, 2);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (8, 4000, 100, 200, 2);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (9, 4500, 100, 200, 2);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (10, 5000, 100, 200, 2);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (11, 5500, 100, 200, 3);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (12, 6000, 100, 200, 3);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (13, 6500, 100, 200, 3);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (14, 7000, 100, 200, 3);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (15, 7500, 100, 200, 3);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (16, 8000, 100, 200, 4);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (17, 8500, 100, 200, 4);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (18, 9000, 100, 200, 4);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (19, 9500, 100, 200, 4);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (20, 10000, 100, 200, 4);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (21, 10500, 100, 200, 5);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (22, 11000, 100, 200, 5);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (23, 11500, 100, 200, 5);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (24, 12000, 100, 200, 5);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (25, 12500, 100, 200, 5);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (26, 13000, 100, 200, 6);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (27, 13500, 100, 200, 6);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (28, 14000, 100, 200, 6);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (29, 14500, 100, 200, 6);
insert into game_song_levels (level, experience, single_experience, two_experience, addition) values (30, 15000, 100, 200, 6);

insert into game_songs (id, name, singer, remark, download_url, page_url) values (1, '苏格兰舞', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (2, '土耳其进行曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (3, '梦幻曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (4, '小夜曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (5, '摇篮曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (6, '秋的私语', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (7, '雪绒花', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (8, '出埃及记', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (9, '渔光曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (10, '水边的阿秋丽娜', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (11, '蓝色多瑙河', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (12, '童年的回忆', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (13, 'Kiss the rain', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (14, '军队进行曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (15, 'River flows in you', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (16, '鸟之诗', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (17, '小步舞曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (18, '星星小夜曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (19, '罗密欧与朱丽叶', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (20, '菊次郎的夏天', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (21, '人生的旋转木马', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (22, '龙猫（散步）', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (23, '龙猫主题曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (24, '千与千寻', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (25, '天鹅湖', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (26, '雪之梦', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (27, '夜的钢琴曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (28, '致爱丽丝', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (29, 'Into the secret realm', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (30, '梁祝', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (31, '拉德斯基进行曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (32, '克劳汀幻想曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (33, 'the moon', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (34, '悲怆奏鸣曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (35, '肖邦小夜曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (36, '友谊地久天长', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (37, 'Papillo', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (38, '小星星', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (39, 'always with me', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (40, '夜曲 trois nocturne op9.1', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (41, 'Innocent', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (42, '千与千寻—不论多少次', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (43, 'My soul', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (44, '橄榄树', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (45, '不能说的秘密-早操', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (46, 'Tears', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (47, '喀秋莎', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (48, '月光协奏曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (49, '欢乐颂', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (50, '苏格兰舞曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (51, '快乐的农夫', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (52, '寂静之声', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (53, '生日快乐 D大调变奏', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (54, '我在那一角落患过伤风', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (55, '虫儿飞', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (56, 'We wish you a merry christmas', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (57, '肖邦 圆舞曲', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (58, '勇敢的骑士', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (59, '鼓浪屿之波', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');
insert into game_songs (id, name, singer, remark, download_url, page_url) values (60, '初雪', '', '', 'http://test.v5.cn/xxxx', 'http://test.v5.cn/xxxx');

insert into game_song_bags (id, name, song_ids, bag_limit, title) values (1, '关卡1', '1,2,3,4,5', '', '初入乐坛');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (2, '关卡2', '6,7,8,9,10', '{"stars":10}', '乐坛新人');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (3, '关卡3', '11,12,13,14,15', '{"three_stars":4}', '街头艺人');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (4, '关卡4', '16,17,18,19,20', '{"level":6}', '伴奏员');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (5, '关卡5', '21,22,23,24,25', '{"stars":44}', '业余演奏员');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (6, '关卡6', '26,27,28,29,30', '{"three_stars":14}', '演奏员');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (7, '关卡7', '31,32,33,34,35', '{"level":10}', '职业演奏家');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (8, '关卡8', '36,37,38,39,40', '{"stars":80}', '乐坛高手');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (9, '关卡9', '41,42,43,44,45', '{"win_num":5, "level":10}', '乐坛达人');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (10, '关卡10', '46,47,48,49,50', '{"three_stars":20, "level":11}', '乐坛皇者');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (11, '关卡11', '51,52,53,54,55', '{"three_stars":30, "stars":120}', '乐坛尊者');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (12, '关卡12', '56,57,58,59,60', '{"stars":135,"level":13}', '乐坛精灵');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (13, '关卡12', '56,57,58,59,60', '{"level":15}', '乐之星');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (14, '关卡12', '56,57,58,59,60', '{"stars":165}', '乐之天皇/乐之天后');
insert into game_song_bags (id, name, song_ids, bag_limit, title) values (15, '关卡15', '56,57,58,59,60', '{"three_stars":50, "level":16}', '无敌乐者');

insert into game_song_score_stars (score, stars) values (500, 1);
insert into game_song_score_stars (score, stars) values (1500, 2);
insert into game_song_score_stars (score, stars) values (3000, 3);

alter table game_players add tie_num int;
alter table game_players add lose_num int;

alter table game_song_board add create_time text;

alter table game_players add power int;
alter table game_players add power_consume_time bigint;
alter table game_players add power_recover_time bigint;

alter table game_info add description text;
alter table game_info add game_servers text
alter table game_info add pic_url text;
alter table game_info alter pic_url type list<text>;






